/**
 * useInvestigationAgent.js — Local keyword-based Investigation Assistant hook
 *
 * Manages conversation state and generates placeholder responses
 * based on keyword matching against the current graph data.
 *
 * No LLM, no API, no backend. Pure client-side simulation.
 */

import { useState, useCallback } from 'react';

/**
 * @param {object} context - Current investigation context
 * @param {number} context.accountCount - Total unique accounts
 * @param {number} context.transactionCount - Total transactions
 * @param {number} context.edgeCount - Number of edges in graph
 * @param {number} context.nodeCount - Number of nodes
 * @param {number} context.ringCount - Number of detected rings
 * @param {string} context.datasetName - Name of loaded dataset
 */
export default function useInvestigationAgent(context = {}) {
    const [messages, setMessages] = useState([]);
    const [isTyping, setIsTyping] = useState(false);

    const generateResponse = useCallback((userMessage) => {
        const msg = userMessage.toLowerCase();
        const {
            accountCount = 0,
            transactionCount = 0,
            edgeCount = 0,
            nodeCount = 0,
            ringCount = 0,
            datasetName = 'N/A',
        } = context;

        // No data loaded
        if (accountCount === 0 && transactionCount === 0) {
            return 'No dataset is currently loaded. Upload a CSV file to begin investigation.';
        }

        // Keyword-based response logic
        if (msg.includes('how many account') || msg.includes('total account') || msg.includes('account count')) {
            return `The current dataset contains ${accountCount.toLocaleString()} unique accounts identified across all transactions.`;
        }

        if (msg.includes('transaction') && (msg.includes('how many') || msg.includes('total') || msg.includes('count'))) {
            return `There are ${transactionCount.toLocaleString()} transactions in the loaded dataset "${datasetName}".`;
        }

        if (msg.includes('ring') || msg.includes('fraud') || msg.includes('cycle')) {
            if (ringCount > 0) {
                return `${ringCount} potential fraud ring(s) have been detected through cycle analysis. Review the DETECTED FINANCIAL NETWORKS table for details.`;
            }
            return 'Detection engine has not yet identified confirmed fraud rings. The SRS-compliant detection algorithms (cycle, smurfing, shell chain) are pending implementation.';
        }

        if (msg.includes('suspici') || msg.includes('score') || msg.includes('risk')) {
            return 'Suspicion scoring engine is in simulation mode. Scores are generated by the temporal propagation simulation. The SRS-compliant scoring methodology (FR-12) is pending implementation.';
        }

        if (msg.includes('summary') || msg.includes('overview') || msg.includes('status')) {
            return `Dataset: "${datasetName}"\n` +
                `Accounts analyzed: ${accountCount.toLocaleString()}\n` +
                `Transactions processed: ${transactionCount.toLocaleString()}\n` +
                `Graph nodes: ${nodeCount.toLocaleString()}\n` +
                `Graph edges: ${edgeCount.toLocaleString()}\n` +
                `Rings detected: ${ringCount}\n\n` +
                `The detection engine is awaiting implementation. Current visualization operates in simulation mode.`;
        }

        if (msg.includes('smurfing') || msg.includes('fan-in') || msg.includes('fan-out')) {
            return 'Smurfing pattern detection (fan-in/fan-out within 72-hour window) is defined in SRS §3.1.3 (FR-7, FR-8) but has not yet been implemented.';
        }

        if (msg.includes('shell') || msg.includes('chain') || msg.includes('layer')) {
            return 'Layered shell network detection (≥3 hops, 2–3 degree intermediaries) is defined in SRS §3.1.3 (FR-9, FR-10) but has not yet been implemented.';
        }

        if (msg.includes('export') || msg.includes('json') || msg.includes('report')) {
            return 'Use the "EXPORT INTEL REPORT" button in the command bar to download a JSON report matching the SRS §3.1.6 schema. Current output contains empty detection arrays until algorithms are implemented.';
        }

        if (msg.includes('help') || msg.includes('what can')) {
            return 'I can answer questions about the current dataset:\n' +
                '• Account and transaction counts\n' +
                '• Dataset summary and status\n' +
                '• Fraud ring information\n' +
                '• Detection engine status\n' +
                '• Export capabilities\n\n' +
                'Note: I am operating in simulation mode. LLM integration is pending.';
        }

        // Default response
        return `Based on the currently uploaded dataset, ${accountCount.toLocaleString()} accounts and ${transactionCount.toLocaleString()} transactions have been analyzed. Fraud pattern detection has not yet been executed. Try asking about "accounts", "transactions", "rings", or "summary".`;
    }, [context]);

    const sendMessage = useCallback((content) => {
        if (!content.trim()) return;

        const userMsg = {
            id: `msg_${Date.now()}_u`,
            role: 'user',
            content: content.trim(),
            timestamp: Date.now(),
        };

        setMessages(prev => [...prev, userMsg]);
        setIsTyping(true);

        // Simulate brief typing delay (300–800ms)
        const delay = 300 + Math.random() * 500;
        setTimeout(() => {
            const response = generateResponse(content);
            const assistantMsg = {
                id: `msg_${Date.now()}_a`,
                role: 'assistant',
                content: response,
                timestamp: Date.now(),
            };
            setMessages(prev => [...prev, assistantMsg]);
            setIsTyping(false);
        }, delay);
    }, [generateResponse]);

    const clearMessages = useCallback(() => {
        setMessages([]);
    }, []);

    return {
        messages,
        isTyping,
        sendMessage,
        clearMessages,
    };
}
